name: Project automations
on:
  pull_request:
    types:
      - opened
      - reopened
      - reviewrequested
# map fields with customized labels
env:
  todo: Todo ✏️
  done: Done ✅
  in_progress: In review

jobs:
  pr_opened_or_reopened_or_reviewrequested:
    name: pr_opened_or_reopened_or_reviewrequested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Move PR to ${{ env.in_progress }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GHPROJECT_TOKEN }}
          user: dranidis
          # organization: sample-org
          project_id: 5
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_progress }} # Target status
  
